	#define K_IF 1
	#define K_ELSE 2
	#define K_WHILE 3
	#define K_DO 4
	#define K_ELIF 5
	#define K_FOR 6
	#define K_BEGIN 7
	#define K_END 8
	#define K_PROCESSOR 9
	#define K_ISA 10
	#define K_CLOCK_SPEED 11
	#define K_L1_MEMORY 12
	#define K_L2_MEMORY 13
	#define K_IS_RUNNING 14
	#define K_SUBMIT_JOBS 15
	#define K_GET_CLOCK_SPEED 16
	#define K_RUN 17
	#define K_DISCARD_JOB 18
	#define K_ARM 19
	#define K_AMD 20
	#define K_CDC 21
	#define K_MIPS 22
	#define K_LINK 23
	#define K_START_POINT 24
	#define K_END_POINT 25
	#define K_BANDWIDTH 26
	#define K_CHANNEL_CAPACITY 27
	#define K_MEMORY 28
	#define K_MEMORY_TYPE 29
	#define K_MEM_SIZE 30
	#define K_GET_AVAILABLE_MEMORY 31
	#define K_JOB 32
	#define K_JOB_ID 33
	#define K_FLOPS_REQUIRED 34
	#define K_DEADLINE 35
	#define K_MEM_REQUIRED 36
	#define K_AFFINITY 37
	#define K_GET_MEMORY 38
	#define K_CLUSTER 39
	#define K_PROCESSORS 40
	#define K_TOPOLOGY 41
	#define K_LINK_BANDWIDTH 42
	#define K_LINK_CAPACITY 43
	#define K_NAME 44
	#define ID 45
	#define INT 46
	#define FLOAT 47
	#define LP 48
	#define RP 49
	#define LB 50
	#define RB 51
	#define STRING 52
	#define LS 53
	#define RS 54
	#define PLUS 55
	#define MINUS 56
	#define MULT 57
	#define DIV 58
	#define RELOP 59
	#define COMMA 60
	#define SEMI 61
	#define COLON 62
	#define ASSIGN 63
	#define L_AND 64
	#define L_OR 65
	#define L_NOT 66
	#define DOT 67
	#define EOFILE 68
	#define K_PRIMARY 69
	#define K_SECONDARY 70
	#define K_CACHE 71
	#define SPACE 72
	#define K_PRINT_STATS 73
	#define K_SCHEDULER 74
	#define K_JOBS 75
	#define K_ALGO 76
	#define K_FCFS 77
	#define K_SJN 78
	#define K_SRT 79
	#define K_RRS 80
	#define K_WAIT 81
	#define K_CLUSTERS 82
	#define K_INT 83
	#define K_BOOL 84
	#define K_FLOAT 85
	#define K_PRINT 86
	#define K_INPUT 87
